default: &default
  appid: "wx8dfc47b762f56954"
  secret: "d50098d88cf618a7415877ddc804c5a5"
  token:  "bBZFTrAbn6Rkt2"
  access_token: "/var/tmp/wechat_access_token"
  jsapi_ticket: "/var/tmp/wechat_jsapi_ticket"

development:
  <<: *default
  trusted_domain_fullname: "http://your_dev.proxy.qqbrowser.cc"

test:
  <<: *default

production:
  <<: *default