default: &default
  appid: "wx3f5e03a894a3a50c"
  secret: "4f261635fa2c1cd96a938667766831df"
  token:  "8jsbVJBivTtCTHKcrsDAHHorm9gNui"
  access_token: "/var/tmp/wechat_access_token"
  jsapi_ticket: "/var/tmp/wechat_jsapi_ticket"
  # encrypt_mode: false
  encoding_aes_key:  "O4a0Lnl0W9wrBT6coewaof0OIa6VJwmZHopqdYFqb3G"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
